modLoader="javafml"
loaderVersion="[65,)"
license="MIT"
clientSideOnly=true

[[mods]]
modId="raissky_secrets"
version="0.1.6"
displayName="RaisSky Secrets"
authors="Raistey"
description='''
Modern Forge 26.2 Hypixel SkyBlock Dungeon secret waypoints.
Auto-detects rooms, shows a clean next-secret HUD, route helpers and hybrid teammate-aware completion detection.
'''

[[dependencies.raissky_secrets]]
    modId="forge"
    mandatory=true
    versionRange="[65.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.raissky_secrets]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,26.3)"
    ordering="NONE"
    side="CLIENT"
