plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

group = 'dev.raistey'
version = '0.2.0'
base { archivesName = 'RaisSky-Secrets-Forge-26.2' }
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }
        register('client')
    }
}
repositories { minecraft.mavenizer(it); maven fg.forgeMaven; maven fg.minecraftLibsMaven; mavenCentral() }
dependencies { implementation minecraft.dependency('net.minecraftforge:forge:26.2-65.1.0') }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
jar {
    manifest {
        attributes([
            'Specification-Title': 'RaisSky Secrets',
            'Specification-Vendor': 'Raistey',
            'Specification-Version': project.version,
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Raistey'
        ])
    }
}
